LANGUAGE_EXTENSIONS = {
    'Python': '.py',
    'Python3': '.py',
    'C++': '.cpp',
    'C': '.c',
    'Java': '.java',
    'C#': '.cs',
    'JavaScript': '.js',
    'Ruby': '.rb',
    'Swift': '.swift',
    'Go': '.go',
    'Kotlin': '.kt',
    'Scala': '.scala',
    'Rust': '.rs',
    'PHP': '.php',
    'TypeScript': '.ts',
    'MySQL': '.sql',
    'MS SQL Server': '.sql',
    'Oracle': '.sql',
}
